name: ExpandingExtensions-Extension
version: 1.0
description: Vanilla+ RPG plugin
main: zinc.doiche.Main
api-version: 1.20
libraries:
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-api:2.15.0
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-core:2.15.0